# Generated by Django 5.1 on 2024-08-08 10:03

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Code",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("code_text", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("language", models.CharField(max_length=50)),
            ],
        ),
    ]
